apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"dagster-daemon","namespace":"dagster"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dagster-daemon"}},"template":{"metadata":{"labels":{"app":"dagster-daemon"}},"spec":{"containers":[{"args":["daemon"],"command":["/entrypoint.sh"],"env":[{"name":"DAGSTER_HOME","value":"/opt/dagster/dagster_home"}],"envFrom":[{"configMapRef":{"name":"dagster-config"}},{"secretRef":{"name":"minio-creds"}}],"image":"dagster-ndvi:latest","imagePullPolicy":"Never","name":"daemon","resources":{"limits":{"memory":"1Gi"},"requests":{"memory":"512Mi"}},"volumeMounts":[{"mountPath":"/opt/dagster/dagster_home","name":"dagster-home"}]}],"volumes":[{"emptyDir":{},"name":"dagster-home"}]}}}}
  creationTimestamp: "2025-04-26T14:56:44Z"
  generation: 1
  name: dagster-daemon
  namespace: dagster
  resourceVersion: "11976"
  uid: 07999399-8584-47c8-abd1-e78539e3c7fb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dagster-daemon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dagster-daemon
    spec:
      containers:
      - args:
        - daemon
        command:
        - /entrypoint.sh
        env:
        - name: DAGSTER_HOME
          value: /opt/dagster/dagster_home
        envFrom:
        - configMapRef:
            name: dagster-config
        - secretRef:
            name: minio-creds
        image: dagster-ndvi:latest
        imagePullPolicy: Never
        name: daemon
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/dagster/dagster_home
          name: dagster-home
        - mountPath: /opt/dagster/dagster_home/dagster.yaml
          name: dagster-yaml
          subPath: dagster.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: dagster-home
      - configMap:
          name: dagster-yaml-config
        name: dagster-yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-26T14:56:44Z"
    lastUpdateTime: "2025-04-26T14:56:45Z"
    message: ReplicaSet "dagster-daemon-785dc6d6df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-27T06:23:48Z"
    lastUpdateTime: "2025-04-27T06:23:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
