apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-yaml-config
  namespace: dagster
data:
  dagster.yaml: |
    scheduler:
      module: dagster.core.scheduler
      class: DagsterDaemonScheduler

    run_coordinator:
      module: dagster.core.run_coordinator
      class: QueuedRunCoordinator

    run_launcher:
      module: dagster.core.launcher
      class: DefaultRunLauncher
      
    telemetry:
      enabled: false 